### ISSUE TITLE
Make the WebPage completely Responsive.

### ISSUE THREAD

**Issue by Aakarsh05** [Aakarsh05/MumbaiChefs#1]
The Webpage should be made responsive for tablets, phones.

**Comment by priyanshu68** [comment]
@Aakarsh05 Hello! I would like to work on this project and make it responsive.

**Comment by Aakarsh05** [comment]
Yeah sure. All the best!! 
Let me know if you are stuck somewhere.

**Comment by priyanshu68** [comment]
hey,Iam new to this or u can say iam learning how to make a website
responsive.
I tried using media queries for different pixel but its not working,i mean
if i fix the responsiveness for mobile devices then switch to tablets ,it
messes up the previous mobile view .
Can u help me with this?

**Comment by Aakarsh05** [comment]
hey! If you know basics of HTML and CSS. You can start using bootstrap. It will be very useful in making this site responsive. This is  a long event, so I suggest you to learn bootstrap.
