### ISSUE TITLE
Better UI.

### ISSUE THREAD

**Issue by Aakarsh05** [Aakarsh05/MumbaiChefs#2]
The UI of this webPage should modified and must look attractive. Explore your creativity on this page.

**Comment by nexi9** [comment]
@Aakarsh05 Hello! I'd like to work on the UI of this project. Is there anything I need to keep in mind while moving forward?

**Comment by Aakarsh05** [comment]
Nothing much....just try to use what you have learned in your frontend. All the best!!!
Let me know if you are stuck somewhere.

**Comment by nexi9** [comment]
can you please check if my pr went through? thanks!

**Comment by Aakarsh05** [comment]
hey! You have done a good job .But I think that selection of font styles and size could have been better and the area in the "review" section is looking a little dull. Some PRs are yet to come on this issue, I would suggest you to look into my suggestions and improve some things. I will Choose among the PRs. If you want to try again, Let me know in the comment.

**Comment by nexi9** [comment]
I'll update it again. Thanks for the feedback

**Comment by Aakarsh05** [comment]
Hey! You have to send me the updated pr by tomorrow as another pr is pending and I have to check between the them.

**Comment by nexi9** [comment]
I've opened another pr and hosted the site.
